name: Auto SEO Article Generator

on:
  schedule:
    # Run every 6 hours (at 00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-article:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-generativeai beautifulsoup4 requests markdown
        pip install python-slugify langdetect langcodes pyyaml python-frontmatter
    
    - name: Create required directories
      run: |
        mkdir -p _posts
        mkdir -p assets/images
        mkdir -p .worker
    
    - name: Generate SEO Article
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        cd .worker
        python auto_generator.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-generated SEO article - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        fi